// <auto-generated />
namespace com.ccvonline.Residency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-alpha3-20222")]
    public sealed partial class AddResidencyAppTables03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddResidencyAppTables03));
        
        string IMigrationMetadata.Id
        {
            get { return "201305070559024_AddResidencyAppTables03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
