// <auto-generated />
namespace com.ccvonline.Residency.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "Rock 0.0")]
    public sealed partial class blank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(blank));
        
        string IMigrationMetadata.Id
        {
            get { return "201306172334119_blank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
